version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "auto-continue-dev"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Security updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group security updates
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security-update"
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
          
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
