# Pre-commit hooks configuration for Auto Continue VS Code Extension
# Prevents secrets and sensitive data from being committed

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-private-key
        name: Detect Private Key
        description: Detects presence of private keys
      - id: check-added-large-files
        name: Check for Large Files
        description: Prevents large files from being committed
        args: ['--maxkb=1000']
      - id: check-case-conflict
        name: Check Case Conflict
        description: Checks for files with names that would conflict on a case-insensitive filesystem
      - id: check-merge-conflict
        name: Check Merge Conflict
        description: Checks for files that contain merge conflict strings
      - id: debug-statements
        name: Debug Statement Check
        description: Checks for debugger imports and breakpoint() calls in Python
      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures files end with a newline
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: Removes trailing whitespace

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect Secrets
        description: Detects secrets in staged files
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  - repo: local
    hooks:
      - id: check-api-keys
        name: Check for API Keys
        entry: bash -c 'if grep -r -i -E "(api[_-]?key|apikey|secret[_-]?key|access[_-]?token|bearer|password)\s*[:=]\s*[\"'\''][^\"'\'']+[\"'\'']" src/ --exclude-dir=node_modules; then echo "❌ Potential API keys or secrets detected! Please remove them."; exit 1; fi'
        language: system
        pass_filenames: false
        
      - id: check-credentials
        name: Check for Hardcoded Credentials  
        entry: bash -c 'if grep -r -i -E "(username|password|passwd|pwd|token|key|secret|credential)\s*[:=]\s*[\"'\''][^\"'\'']+[\"'\'']" src/ --exclude-dir=node_modules --exclude="*.test.ts" --exclude="*.spec.ts"; then echo "❌ Potential hardcoded credentials detected! Please remove them."; exit 1; fi'
        language: system
        pass_filenames: false

      - id: check-env-files
        name: Check for Environment Files
        entry: bash -c 'if find . -name ".env*" -not -path "./node_modules/*" -not -name ".env.example" -not -name ".env.template" | grep -q .; then echo "❌ Environment files detected! Add them to .gitignore."; exit 1; fi'
        language: system
        pass_filenames: false

      - id: check-security-patterns
        name: Check for Security Anti-patterns
        entry: bash -c 'if grep -r -i -E "(console\.log|console\.error|console\.warn).*(\bpassword\b|\btoken\b|\bkey\b|\bsecret\b)" src/; then echo "❌ Potential logging of sensitive data detected!"; exit 1; fi'
        language: system  
        pass_filenames: false
