name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npm run check-types
      
    - name: Build
      run: node esbuild.js
      
    - name: Lint
      run: npm run lint
      continue-on-error: true
      
    - name: Security audit
      run: npm audit --audit-level moderate
      continue-on-error: true
      
    - name: Package
      run: npm run package
      continue-on-error: true

  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run custom security checks
      run: |
        if [ -f "scripts/security-check.sh" ]; then
          bash scripts/security-check.sh
        else
          echo "No custom security script found"
        fi
